using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GunController_kjw : MonoBehaviour
{
    [SerializeField]
    private Gun_kjw currentGun; // í˜„ì¬ ë“¤ê³  ìˆëŠ” ì´. ğŸ“œGun.cs ê°€ í• ë‹¹ ë¨.

    private float currentFireRate; // ì´ ê°’ì´ 0 ë³´ë‹¤ í° ë™ì•ˆì—ëŠ” ì´ì•Œì´ ë°œì‚¬ ë˜ì§€ ì•ŠëŠ”ë‹¤. ì´ˆê¸°ê°’ì€ ì—°ì‚¬ ì†ë„ì¸ ğŸ“œGun.csì˜ fireRate 

    private bool isReload = false;  // ì¬ì¥ì „ ì¤‘ì¸ì§€.

    private RaycastHit hitInfo;  // ì´ì•Œì˜ ì¶©ëŒ ì •ë³´

    [SerializeField]
    private Camera theCam;  // ì¹´ë©”ë¼ ì‹œì ì—ì„œ ì • ì¤‘ì•™ì— ë°œì‚¬í•  ê±°ë¼ì„œ

    private bool isFineSightMode = false;

    [SerializeField]
    private Vector3 originPos;  // ì›ë˜ ì´ì˜ ìœ„ì¹˜(ì •ì¡°ì¤€ í•´ì œí•˜ë©´ ë‚˜ì¤‘ì— ëŒì•„ì™€ì•¼ í•˜ë‹ˆê¹Œ)

    private AudioSource audioSource;  // ë°œì‚¬ ì†Œë¦¬ ì¬ìƒê¸°

    int layerMask;


    void Start()
    {
        audioSource = GetComponent<AudioSource>();
        layerMask = 1 << LayerMask.NameToLayer("Monster");
    }

    void Update()
    {
        GunFireRateCalc();
        TryFire();
        TryReload();
    }

    private void GunFireRateCalc()
    {
        if (currentFireRate > 0)
            currentFireRate -= Time.deltaTime;  // ì¦‰, 1 ì´ˆì— 1 ì”© ê°ì†Œì‹œí‚¨ë‹¤.
    }

    private void TryFire()  // ë°œì‚¬ ì…ë ¥ì„ ë°›ìŒ
    {
        if (Input.GetButton("Fire1") && currentFireRate <= 0 && !isReload)
        {
            Fire();
        }
    }

    private void Fire()  // ë°œì‚¬ë¥¼ ìœ„í•œ ê³¼ì •
    {
        if (!isReload)
        {
            if (currentGun.currentBulletCount > 0)
                Shoot();
            else
            {
                StartCoroutine(ReloadCoroutine());
            }
        }
    }

    private void Shoot()  // ì‹¤ì œ ë°œì‚¬ ë˜ëŠ” ê³¼ì •
    {
        currentGun.currentBulletCount--;
        currentFireRate = currentGun.fireRate;  // ì—°ì‚¬ ì†ë„ ì¬ê³„ì‚°
        PlaySE(currentGun.fire_Sound);
        currentGun.anim.SetTrigger("Shoot");
        currentGun.anim.SetTrigger("Idle");
        currentGun.muzzleFlash.Play();

        // í”¼ê²© ì²˜ë¦¬
        Hit();


        // ì´ê¸° ë°˜ë™ ì½”ë£¨í‹´ ì‹¤í–‰
        StopAllCoroutines();
        StartCoroutine(RetroActionCoroutine());

        Debug.Log("ì´ì•Œ ë°œì‚¬ í•¨");
    }

    private void Hit()
    {
        // ì¹´ë©”ë¼ ì›”ë“œ ì¢Œí‘œ!! (localPositionì´ ì•„ë‹˜)
        if (Physics.Raycast(theCam.transform.position, theCam.transform.forward, out hitInfo, currentGun.range, layerMask))
        {
            Debug.Log(hitInfo.transform.name);
           
            hitInfo.transform.GetComponent<Mob>().Damage(currentGun.damage, transform.position);
            
        }
    }

        

    private void TryReload()
    {
        if (Input.GetKeyDown(KeyCode.R) && !isReload && currentGun.currentBulletCount < currentGun.reloadBulletCount)
        {
            StartCoroutine(ReloadCoroutine());
        }
    }

    IEnumerator ReloadCoroutine()
    {
        if (currentGun.carryBulletCount > 0)
        {
            isReload = true;
            currentGun.anim.SetTrigger("Reload");
             
            currentGun.carryBulletCount += currentGun.currentBulletCount;
            currentGun.currentBulletCount = 0;

            yield return new WaitForSeconds(currentGun.reloadTime);  // ì¬ì¥ì „ ì• ë‹ˆë©”ì´ì…˜ì´ ë‹¤ ì¬ìƒë  ë™ì•ˆ ëŒ€ê¸°

            if (currentGun.carryBulletCount >= currentGun.reloadBulletCount)
            {
                currentGun.currentBulletCount = currentGun.reloadBulletCount;
                currentGun.carryBulletCount -= currentGun.reloadBulletCount;
            }
            else
            {
                currentGun.currentBulletCount = currentGun.carryBulletCount;
                currentGun.carryBulletCount = 0;
            }

            isReload = false;
        }
        else
        {
            Debug.Log("ì†Œìœ í•œ ì´ì•Œì´ ì—†ìŠµë‹ˆë‹¤.");
        }
    }

    public Gun_kjw GetGun()
    {
        return currentGun;
    }




    IEnumerator RetroActionCoroutine()
    {
        Vector3 recoilBack = new Vector3(currentGun.retroActionForce, originPos.y, originPos.z);     // ì •ì¡°ì¤€ ì•ˆ í–ˆì„ ë•Œì˜ ìµœëŒ€ ë°˜ë™
       
        if (!isFineSightMode)  // ì •ì¡°ì¤€ì´ ì•„ë‹Œ ìƒíƒœ
        {
            // ë°˜ë™ ì‹œì‘
            while (currentGun.transform.localPosition.x <= currentGun.retroActionForce - 0.02f)
            {
                currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition, recoilBack, 0.4f);
                yield return null;
            }

            // ì›ìœ„ì¹˜
            while (currentGun.transform.localPosition != originPos)
            {
                currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition, originPos, 0.1f);
                yield return null;
            }
        }
        

    }

    private void PlaySE(AudioClip _clip)  // ë°œì‚¬ ì†Œë¦¬ ì¬ìƒ
    {
        audioSource.clip = _clip;
        audioSource.Play();
    }
}
