using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GunController : MonoBehaviour
{
    [SerializeField]
    private Gun currentGun; // í˜„ì¬ ë“¤ê³  ìˆëŠ” ì´. ğŸ“œGun.cs ê°€ í• ë‹¹ ë¨.
    public GameObject bulletPref;
    public Transform shotPos;
    public Transform player;
    private float currentFireRate; // ì´ ê°’ì´ 0 ë³´ë‹¤ í° ë™ì•ˆì—ëŠ” ì´ì•Œì´ ë°œì‚¬ ë˜ì§€ ì•ŠëŠ”ë‹¤. ì´ˆê¸°ê°’ì€ ì—°ì‚¬ ì†ë„ì¸ ğŸ“œGun.csì˜ fireRate 
    public Rigidbody bulletRig;
    public float bulletSpeed = 9.0f;

    private AudioSource audioSource;  // ë°œì‚¬ ì†Œë¦¬ ì¬ìƒê¸°

    void Start()
    {
        audioSource = GetComponent<AudioSource>();
    }

    void Update()
    {
        GunFireRateCalc();
        TryFire();
    }

    private void GunFireRateCalc()
    {
        if (currentFireRate > 0)
            currentFireRate -= Time.deltaTime;  // ì¦‰, 1 ì´ˆì— 1 ì”© ê°ì†Œì‹œí‚¨ë‹¤.
    }

    private void TryFire()  // ë°œì‚¬ ì…ë ¥ì„ ë°›ìŒ
    {
        if (Input.GetButtonDown("Fire1") && currentFireRate <= 0)
        {
            Fire();
        }
    }

    private void Fire()  // ë°œì‚¬ë¥¼ ìœ„í•œ ê³¼ì •
    {
        Vector3 dir = shotPos.transform.position;
        // dir.z += 0.7f;
        Rigidbody rg = (Rigidbody)Instantiate(bulletRig, dir, player.transform.rotation);
        rg.AddForce(shotPos.forward * 80, ForceMode.Impulse);
        // rg.velocity = transform.TransformDirection(new Vector3(0, 0, bulletSpeed));
        // rig.AddForce(shotPos.forward * 5, ForceMode.Impulse);
        Shoot();
    }

    private void Shoot()  // ì‹¤ì œ ë°œì‚¬ ë˜ëŠ” ê³¼ì •
    {
        /*PlaySE(currentGun.fire_Sound);
        currentGun.muzzleFlash.Play();
        currentFireRate = currentGun.fireRate;
        GameObject bullet = Instantiate(bulletPref, player.transform.position, player.transform.rotation);
        bullet.transform.position = shotPos.transform.position;*/
        Debug.Log("ì´ì•Œ ë°œì‚¬ í•¨");
    }

    private void PlaySE(AudioClip _clip)  // ë°œì‚¬ ì†Œë¦¬ ì¬ìƒ
    {
        audioSource.clip = _clip;
        audioSource.Play();
    }
}
