using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GunController : MonoBehaviour
{
    [SerializeField]
    private Gun currentGun; // í˜„ì¬ ë“¤ê³  ìˆëŠ” ì´. ğŸ“œGun.cs ê°€ í• ë‹¹ ë¨.

    private float currentFireRate; // ì´ ê°’ì´ 0 ë³´ë‹¤ í° ë™ì•ˆì—ëŠ” ì´ì•Œì´ ë°œì‚¬ ë˜ì§€ ì•ŠëŠ”ë‹¤. ì´ˆê¸°ê°’ì€ ì—°ì‚¬ ì†ë„ì¸ ğŸ“œGun.csì˜ fireRate 

    private AudioSource audioSource;  // ë°œì‚¬ ì†Œë¦¬ ì¬ìƒê¸°

    void Start()
    {
        audioSource = GetComponent<AudioSource>();
    }

    void Update()
    {
        GunFireRateCalc();
        TryFire();
    }

    private void GunFireRateCalc()
    {
        if (currentFireRate > 0)
            currentFireRate -= Time.deltaTime;  // ì¦‰, 1 ì´ˆì— 1 ì”© ê°ì†Œì‹œí‚¨ë‹¤.
    }

    private void TryFire()  // ë°œì‚¬ ì…ë ¥ì„ ë°›ìŒ
    {
        if (Input.GetButton("Fire1") && currentFireRate <= 0)
        {
            Fire();
        }
    }

    private void Fire()  // ë°œì‚¬ë¥¼ ìœ„í•œ ê³¼ì •
    {
        currentFireRate = currentGun.fireRate;
        Shoot();
    }

    private void Shoot()  // ì‹¤ì œ ë°œì‚¬ ë˜ëŠ” ê³¼ì •
    {
        PlaySE(currentGun.fire_Sound);
        currentGun.muzzleFlash.Play();
        Debug.Log("ì´ì•Œ ë°œì‚¬ í•¨");
    }

    private void PlaySE(AudioClip _clip)  // ë°œì‚¬ ì†Œë¦¬ ì¬ìƒ
    {
        audioSource.clip = _clip;
        audioSource.Play();
    }
}
